# Generated by Django 5.0.4 on 2024-05-01 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=300)),
                ('area', models.FloatField(default=0)),
                ('district', models.CharField(default='', max_length=100)),
                ('agricultural_zone', models.CharField(default='', max_length=100)),
                ('density_of_cultivation', models.CharField(default='', max_length=100)),
                ('acclimatization', models.CharField(default='', max_length=100)),
                ('region', models.CharField(default='', max_length=100)),
                ('requirements_for_monthly', models.IntegerField(default=0)),
                ('requirements_for_annual', models.IntegerField(default=0)),
                ('description', models.TextField(default='')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
