# Generated by Django 5.0.3 on 2024-05-17 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0004_land_branch_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='requirements_for_annual',
        ),
        migrations.RemoveField(
            model_name='land',
            name='requirements_for_monthly',
        ),
    ]
