# Generated by Django 5.0.3 on 2024-05-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_agent',
            field=models.BooleanField(default=True),
        ),
    ]
