# Generated by Django 5.0.4 on 2024-05-01 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_plant_created_at_plant_updated_at'),
        ('varieties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variety',
            name='plant_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='plants.plant'),
        ),
    ]
