# Generated by Django 5.0.4 on 2024-05-01 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lands', '0001_initial'),
        ('plants', '0002_plant_created_at_plant_updated_at'),
        ('varieties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandsPlants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_quantity', models.IntegerField()),
                ('description', models.TextField()),
                ('land_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lands.land')),
                ('plant_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.plant')),
                ('variety_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='varieties.variety')),
            ],
        ),
    ]
