# Generated by Django 5.0.3 on 2024-05-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands_plants', '0002_rename_landsplants_landplant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landplant',
            name='description',
        ),
        migrations.RemoveField(
            model_name='landplant',
            name='plant_quantity',
        ),
        migrations.AddField(
            model_name='landplant',
            name='requirements_for_annual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='landplant',
            name='requirements_for_monthly',
            field=models.IntegerField(default=0),
        ),
    ]
