# Generated by Django 5.0.3 on 2024-05-08 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='counrty',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='staus',
            new_name='status',
        ),
    ]
