# Generated by Django 5.0.3 on 2024-05-21 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Agent',
            new_name='agent',
        ),
    ]
